# Generated by Django 5.2.6 on 2025-09-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=512, null=True)),
                ('color', models.CharField(blank=True, max_length=128, null=True)),
                ('memory', models.CharField(blank=True, max_length=128, null=True)),
                ('seller', models.CharField(blank=True, max_length=256, null=True)),
                ('price', models.CharField(blank=True, max_length=128, null=True)),
                ('special_price', models.CharField(blank=True, max_length=128, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('product_code', models.CharField(blank=True, max_length=128, null=True)),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=256, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=128, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=128, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
